Update playwright.yml

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,7 +1,9 @@
-name: Run Playwright Script with PM2
+name: Run Playwright Script
 
 on:
   workflow_dispatch:  # Ручной запуск
+  schedule:
+    - cron: '*/2 * * * *'  # Запускать каждые 2 минут
 
 jobs:
   test:
@@ -11,7 +13,23 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
-          fetch-depth: 0
+          fetch-depth: 0  # Загружаем весь репозиторий
+
+      - name: Debug working directory
+        run: |
+          echo "Текущая директория:"
+          pwd
+          echo "Файлы в текущей директории:"
+          ls -la
+
+      - name: Debug all files
+        run: |
+          echo "Список всех файлов в репозитории:"
+          find . -type f
+
+      - name: Test proxy connection
+        run: |
+          curl -x s2.thisproxy.works:2017 -U sparkly_avocado_1:TYLeGIsEuTur -I http://osdon.ru/ || echo "Proxy failed!"
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
@@ -21,15 +39,9 @@ jobs:
       - name: Install dependencies
         run: |
           npm install
-          npm install -g pm2  # Устанавливаем PM2 глобально
           npx playwright install --with-deps
         working-directory: .github/workflows
 
-      - name: Run Playwright script with PM2
-        run: |
-          pm2 start index.js --name "playwright-script" --restart-delay 3000
+      - name: Run Playwright script
+        run: node index.js
         working-directory: .github/workflows
-
-      - name: Display PM2 status
-        run: |
-          pm2 status
